function.geoinfo.js
#1980
https://github.com/WizardFactory/TodayWeather/issues/1980
=> 404 Error when lat = 0 and lng = 0

handler.js
#2000
use CDN URL for kma/addr
https://github.com/WizardFactory/TodayWeather/issues/2000
=> check error when fail to connect tw-service

handler.js, package.json
#2000
use tw-service (doesn't use CDN)
https://github.com/WizardFactory/TodayWeather/issues/2000
=> add dns cache

serverless.yml
Max Memory Used: 55 MB 이므로 용량 조정
메모리양에 따라 VM성능과 가격이 조정됨
=> set memorySize to 128

function.weather.js, handler.js, test/e2e/test.e2e.function.weather.js, test/test.function.weather.js
#2000
에러발생빈도 차이가 나지 않으면 rollback 예정
https://github.com/WizardFactory/TodayWeather/issues/2000
=> ipUrl -> domainUrl 순서로 request

controller.daum.js
#2012
https://github.com/WizardFactory/TodayWeather/issues/2012
=> 일본지역을 DAUM에서 남해로 전달되는 경우 처리

.travis.yml, config.js, function.geoinfo.js, function.weather.js, test/e2e/test.e2e.function.weather.js, test/test.function.weather.js
#2016
https://github.com/WizardFactory/TodayWeather/issues/2016
=> weather data 못 가지고 오는 경우 예외처리

controller.address.dynamodb.js, controller.daum.js, serverless.yml
#2084
https://github.com/WizardFactory/TodayWeather/issues/2084
=> 보완 : 나라정보없는 경우, 주소정보 여러개인경우

serverless.yml
=> geocode api도 version 지원하게 수정

serverless.yml
#1895
WizardFactory/TodayWeather#1895
=> 모든 api에 대하여 version 지원하게 수정

controller.daum.js
#2135
https://github.com/WizardFactory/TodayWeather/issues/2135
=> check nameX's length before inserting kmaAddress

controller.darksky.js, controller.daum.js, controller.geoapi.js, controller.geocode.dynamodb.js, controller.google.js
#2008
- new geocode api
- new attribute provider for geoinfo
https://github.com/WizardFactory/TodayWeather/issues/2008
=> new geocode api

function.geoinfo.js
#2167 #1701
- geocode/coord 요청시 kmaAddress가 있다면 추가
https://github.com/WizardFactory/TodayWeather/issues/1701
https://github.com/WizardFactory/TodayWeather/issues/2167
=> kmaAddress 추가

controller.dynamodb.js, controller.geocode.dynamodb.js
#2033
async timout과 retry를 사용하고 강제 종료 및 재시도
https://github.com/WizardFactory/TodayWeather/issues/2033
=> dynamodb 응답 없는 문제

kaqfs/controller.s3.js, kaqfs/scrape.kaqfs.js, serverless.yml, test/e2e_local/test.e2e.controller.s3.js
- controller.s3
- new copy()
- scrape.kaqfs
- get region, bucket from config
- serverless.yml
- update hourly
=> TW-184 매시간 갱신 및 시간별 백업

kaqfs/scrape.kaqfs.js, serverless.yml, test/e2e_local/test.e2e.scrape.kaqfs.js
- model 마다 gif 업데이트 속도가 다름
- modelimg별로 text detection하여 업로드
=> TW-224 KAQ 미세먼지 PM2.5 예보 데이터 오류

kaqfs/scrape.kaqfs.js, serverless.yml
- 각 image마다 OCR 작동
- image별로 업데이트 시간이 다른 경우가 있음
- gathering 조정
- modelimg, modelimg_CASE4
- area 09KM
- scraping time 조정
- folderName 변경
- OCR에서 잘못된 space를 인식함
=> TW-224 pollutant별 text read

kaqfs/scrape.kaqfs.js
=> TW-207 bucket name error

geoinfo/handler.js, package.json, serverless.yml, weather/handler.js
- add aws-xray-sdk
- fix webpack version
- add http trace to geoinfo
=> Tw 246 x ray

aqicn/request.aqicn.js, geoinfo/controller.externalapi.js, serverless.yml, weather/function.weather.js
- memsize to 1024
- add gzip to options of request
=> TW-246 up memsize and gzip

config.js, geoinfo/controller.geoapi.js, geoinfo/controller.kakao.js, package.json, test/test.controller.geoapi.js, test/test.controller.kakao.js, test/test.function.weather.js, weather/function.weather.js
- Applied Kakao API
- DAUM API will be deprecated soon, so it should be replaced by Kakao API
=> TW-430 Applied Kakao API
